### ISSUE TITLE
variation in location role string

### ISSUE THREAD

**Issue by marjorief** [e-spaulding/xpo#11]
We see both AM_loc and AM_loc_location in the current version of the overlay. It would probably be helpful to standardize on one.

**Comment by e-spaulding** [comment]
I realized after I "fixed" this that I may have misunderstood the issue. I saw that there were duplicate arguments in which we have one argument that is `AM_loc` in both the `short_name` and `name` slot, and then another, more descriptive argument which has a longer `name`. So I removed the less descriptive duplicate. (See the diff in the commit for examples.) Is this what you meant to address? (Either way, it needed to be fixed! 😄)

**Comment by marjorief** [comment]
@aphedges --- can you work with @e-spaulding  to answer the question.

**Comment by aphedges** [comment]
@marjorief, I was actually almost done with my response when you posted your comment! :joy:

The problem that @marjorief noticed was that the role for `Q2956685` is `AM_loc`, but the corresponding role for `Q28777323` is `AM_loc__location`. Each only has a single `AM_loc.*` role, but the former qnode has no longer version of the role name. Here is the extracted JSON (from the most recent release) for easier viewing of the problem:

```json
{
  "events": {
    "DWD_Q2956685": {
      "type": "event_type",
      "name": "disruption",
      "wd_node": "Q2956685",
      "wd_description": "event which interferes with an ongoing process",
      "overlay_parents": [
        {
          "name": "occurrence",
          "wd_node": "Q1190554"
        }
      ],
      "pb_roleset": "disrupt.01",
      "curated_by": "CMU",
      "arguments": [
        {
          "name": "A0_pag_disrupter",
          "short_name": "A0_pag",
          "constraints": [
            {
              "name": "person",
              "wd_node": "Q215627"
            },
            {
              "name": "group_of_humans",
              "wd_node": "Q16334295"
            }
          ]
        },
        {
          "name": "A1_ppt_entity_disrupted",
          "short_name": "A1_ppt",
          "constraints": []
        },
        {
          "name": "AM_loc",
          "constraints": [],
          "short_name": "AM_loc"
        }
      ],
      "similar_nodes": []
    },
    "DWD_Q28777323": {
      "type": "event_type",
      "name": "breakdown",
      "wd_node": "Q28777323",
      "wd_description": "damage or breakage event that compromises the functioning of a system or a machine",
      "overlay_parents": [
        {
          "name": "failure",
          "wd_node": "Q1121708"
        }
      ],
      "pb_roleset": "break_down.12",
      "curated_by": "xpo",
      "arguments": [
        {
          "name": "A1_ppt_patient_thing_broken_down",
          "constraints": [
            {
              "name": "physical_object",
              "wd_node": "Q223557"
            }
          ],
          "short_name": "A1_ppt"
        },
        {
          "name": "A0_pag_agent_cause_of_breaking",
          "constraints": [
            {
              "name": "organism",
              "wd_node": "Q7239"
            },
            {
              "name": "machine",
              "wd_node": "Q11019"
            },
            {
              "name": "person",
              "wd_node": "Q215627"
            },
            {
              "name": "group_of_humans",
              "wd_node": "Q16334295"
            }
          ],
          "short_name": "A0_pag"
        },
        {
          "name": "AM_loc__location",
          "constraints": [],
          "short_name": "AM_loc"
        }
      ]
    }
  }
}
```

I know this is a separate problem, but looking at this JSON, I can see that the order of the `name`, `constraints`, and `short_name` fields are not consistent across objects, even within the same array. `short_name` should probably always be before `constraints` because it's easy to miss a short field after a long array. I can create a separate issue for this, if you want.

**Comment by e-spaulding** [comment]
Thank you! We decided to standardize the string to `AM_loc` since the other, longer strings do not add any additional information. I also went ahead and fixed the ordering of the argument fields according to your suggestion.

**Comment by aphedges** [comment]
Thank you very much! From a quick inspection, these changes look good to me.

**Comment by marjorief** [comment]
I'm happy with these.  If memory serves some of the KAIROS teams really wanted "real English words", so it probably makes sense for this decision to broadcast to the OWG.
