### ISSUE TITLE
Fix moved entity qnodes in v5.4

### ISSUE THREAD

**Issue by aphedges** [e-spaulding/xpo#19]
Although #13 was merged and is listed in the changelog, the changes were not applied properly:

- right_Q22059430 --> right_Q2386606: Both qnodes now have an entry in the overlay.
- equipment_Q16798631 --> equipment_Q10273457: The new qnode is not present in the overlay.

I suspect there was a problem when merging.

**Comment by e-spaulding** [comment]
Oops. I'll fix this and release the fix in a week or so along with some new nodes we were requested to add!

**Comment by aphedges** [comment]
I can confirm that this is fixed in <https://github.com/e-spaulding/xpo/blob/7c8f893fea0540111f7ff8d30df06fda79ec2067/xpo_v5.4.1.json>. Do you know when v5.4.1 will be officially released?

**Comment by e-spaulding** [comment]
Sorry it took so long. Just published! (v5.4.2)...

**Comment by aphedges** [comment]
Not a problem. Thanks!
