### ISSUE TITLE
Problems with v5.4.3

### ISSUE THREAD

**Issue by aphedges** [e-spaulding/xpo#24]
There are two qnodes that could potentially be fixed:

- `Q10676833` in the overlay and Wikidata is `Q424737` in DWD
- `Q12779002` in the overlay and Wikidata is `Q99348376` in DWD

In both cases, Wikidata has redirects, so it should be fine to replace them with their DWD counterparts.

Although they would be good to fix, we are unlikely to use either of these, so it doesn't particularly matter if you fix them or not.

---

The following qnodes do not appear to be present in DWD at all:

- `Q112803924`
- `Q113280972`
- `Q113594218`
- `Q113688270`
- `Q113884603`
- `Q114019691`
- `Q115158676`
- `Q115287494`
- `Q115298947`
- `Q115397708`
- `Q115667577`
- `Q115912847`
- `Q116160778`
- `Q116446192`
- `Q116741265`
- `Q116771298`
- `Q116812968`

There isn't really any workaround, so it doesn't really matter if they would be useful to us or not.

**Comment by e-spaulding** [comment]
Made the changes you suggested. Thank you for pointing these out!
