### ISSUE TITLE
Problems with v5.4.4

### ISSUE THREAD

**Issue by aphedges** [e-spaulding/xpo#27]
There are three qnodes that could potentially be fixed:

- `Q6056746` in the overlay and Wikidata is `Q18812548` in DWD
- `Q11620540` in the overlay and Wikidata is `Q11868838` in DWD
- `Q12819913` in the overlay and Wikidata is `Q23009459` in DWD

In all three cases, Wikidata has redirects, so it should be fine to replace them with their DWD counterparts.

I'm not sure if we are using them now, but they seem like ones relevant to the program's domains.

**Comment by e-spaulding** [comment]
I replaced them with their DWD nodes. Thank you for your patience!
