### ISSUE TITLE
Problem with v5.4.6

### ISSUE THREAD

**Issue by aphedges** [e-spaulding/xpo#31]
One of the problems I reported in #24 reappeared in 08c037e6d47545e1173615d01dbf819ebde9f8d2. The problem is relatively simple to fix because it just requires changing WD_Q12779002 --> DWD_Q99348376.

This isn't a high priority, though. I don't think it's a qnode we are likely to use.

**Comment by e-spaulding** [comment]
Fixed in 5.4.7!

**Comment by aphedges** [comment]
I can confirm that. Thanks!
