### ISSUE TITLE
LESTAT Qnodes

### ISSUE THREAD

**Issue by e-spaulding** [e-spaulding/xpo#6]
LESTAT curators have found many qnodes not in the DWD overlay that we should consider adding. Links below.

We can expect an update with more qnode suggestions in early November.

[Events](https://docs.google.com/spreadsheets/d/15uQcrgT8O2X84rX2w78zlcqugGhpveXm/edit?usp=sharing&ouid=116351218637855731324&rtpof=true&sd=true)

[Entities](https://docs.google.com/spreadsheets/d/1pFqzOpZHspD0it54OzYlwW1BJwoccyd7/edit?usp=sharing&ouid=116351218637855731324&rtpof=true&sd=true)

**Comment by aphedges** [comment]
I just skimmed the spreadsheets, and it seems there was an import issue with encoding. The text `résumé` is shown as `r√©sum√©`. For the original text, see [event_qnodes.csv](https://github.com/e-spaulding/xpo/files/9700407/event_qnodes.csv) and [entity_qnodes.csv](https://github.com/e-spaulding/xpo/files/9700408/entity_qnodes.csv).

**Comment by e-spaulding** [comment]
Thank you very much!
