### ISSUE TITLE
Qnode IDs deprecated from WD

### ISSUE THREAD

**Issue by e-spaulding** [e-spaulding/xpo#8]
The following DWD nodes are deprecated from WD. If you query WD with these IDs, it will redirect you to the updated ID.

```
DWD Node	(Deprecated) Qnode ID	Name
DWD_Q28777323	Q28777323	creation
DWD_Q16837407	Q16837407	ballot_initiative
DWD_Q23009459	Q23009459	conjugation
DWD_Q11868838	Q11868838	faith_healing
DWD_Q22905880	Q22905880	interview
DWD_Q30028999	Q30028999	practice
DWD_Q12826913	Q12826913	search
DWD_Q3077373	Q3077373	test_drive
DWD_Q49849	Q49849	appliance
```

We should update these IDs for the next release.

**Comment by aphedges** [comment]
Although these qnodes are deprecated in Wikidata, the changes haven't yet made it into DWD. For example, [Q28777323](https://dwd.isi.edu/browser/Q28777323) is in DWD but its replacement in Wikidata, [Q19977811](https://www.wikidata.org/wiki/Q19977811), is not. These updates should probably be delayed until after DWD is next updated.
